import React, { useState } from "react";

const SearchBar = ({ onLocationSelect }) => {
  const [searchTerm, setSearchTerm] = useState("");
  const [suggestions, setSuggestions] = useState([]);

  const handleSearch = (event) => {
    const value = event.target.value.toLowerCase();
    setSearchTerm(value);

    const cities = [
      "Tokyo",
      "Delhi",
      "Shanghai",
      "Sao Paulo",
      "Mumbai",
      "Mexico City",
      "Beijing",
      "Osaka",
      "Cairo",
      "New York",
      "Dhaka",
      "Karachi",
      "Buenos Aires",
      "Istanbul",
      "Chongqing",
      "Kolkata",
      "Manila",
      "Lagos",
      "Rio de Janeiro",
      "Tianjin",
      "Kinshasa",
      "Guangzhou",
      "Los Angeles",
      "Moscow",
      "Shenzhen",
      "Lahore",
      "Bangkok",
      "Jakarta",
      "Seoul",
      "Bangalore",
      "Chennai",
      "Lima",
      "Hyderabad",
      "Johannesburg",
      "Tehran",
      "Wuhan",
      "Ho Chi Minh City",
      "Luanda",
      "Ahmedabad",
      "Harbin",
      "Baghdad",
      "Surat",
      "Riyadh",
      "Santiago",
      "Pune",
      "Singapore",
      "Madrid",
      "Toronto",
      "Frankfurt",
      "Yangon",
      "Ankara",
      "Munich",
      "Paris",
      "Sydney",
      "Washington D.C.",
      "Seattle",
      "Dallas",
      "Atlanta",
      "Miami",
      "Philadelphia",
      "San Francisco",
      "Boston",
      "Phoenix",
      "Detroit",
      "Houston",
      "Riverside",
      "Chicago",
      "Montreal",
      "Vancouver",
      "Ottawa",
      "Calgary",
      "Edmonton",
      "Quebec City",
      "Winnipeg",
      "Halifax",
      "St. John's",
      "Santiago de Cuba",
      "Santo Domingo",
      "Havana",
      "Port-au-Prince",
      "Kingston",
      "San Juan",
      "Bridgetown",
      "Hamilton",
      "Nassau",
      "San Jose",
      "Belize City",
      "Tegucigalpa",
      "Managua",
      "San Salvador",
      "Panama City",
      "Willemstad",
      "Oranjestad",
      "Philipsburg",
      "Basseterre",
      "Roseau",
      "Saint John's",
      "Castries",
      "Saint George's",
      "Kingstown",
      "Port of Spain",
      "Caracas",
      "Bogotá",
      "La Paz",
      "Asuncion",
      "Montevideo",
      "Brasilia",
      "Rio de Janeiro",
      "São Paulo",
      "Santiago",
      "Quito",
      "Guayaquil",
      "Cusco",
      "Machu Picchu",
      "Cartagena",
      "Cancun",
      "Tulum",
      "Puerto Vallarta",
      "Guadalajara",
      "Puebla",
      "Merida",
      "Cabo San Lucas",
      "Los Cabos",
      "Playa del Carmen",
      "Nassau",
      "Freeport",
      "Paradise Island",
      "Eleuthera",
      "Harbour Island",
      "Bimini",
      "New Providence",
      "Bridgetown",
      "Kingston",
      "Port-au-Prince",
      "San Juan",
      "Santo Domingo",
      "Havana",
      "San Jose",
      "Managua",
      "Tegucigalpa",
      "Panama City",
      "Belize City",
      "Willemstad",
      "Oranjestad",
      "Philipsburg",
      "Basseterre",
      "Roseau",
      "Saint John's",
      "Castries",
      "Saint George's",
      "Kingstown",
      "Port of Spain",
      "Caracas",
      "Bogotá",
      "Quito",
      "La Paz",
      "Asuncion",
      "Montevideo",
      "Brasilia",
      "Rio de Janeiro",
      "São Paulo",
      "Santiago",
      "Cusco",
      "Machu Picchu",
      "Cartagena",
      "Cancun",
      "Tulum",
      "Puerto Vallarta",
      "Puebla",
      "Merida",
      "Cabo San Lucas",
      "Los Cabos",
      "Playa del Carmen",
      "Nassau",
      "Freeport",
      "Paradise Island",
      "Eleuthera",
      "Harbour Island",
      "Bimini",
      "New Providence",
      "George Town",
      "Bridgetown",
      "Kingston",
      "Port-au-Prince",
      "San Juan",
      "Santo Domingo",
      "Havana",
      "San Jose",
      "Managua",
      "Tegucigalpa",
      "Guatemala City",
      "Panama City",
      "Belize City",
      "Willemstad",
      "Oranjestad",
      "Philipsburg",
      "Basseterre",
      "Roseau",
      "Saint John's",
      "Castries",
      "Saint George's",
      "Kingstown",
      "Port of Spain",
      "Caracas",
      "Bogotá",
      "Quito",
      "La Paz",
      "Asuncion",
      "Montevideo",
      "Brasilia",
      "Rio de Janeiro",
      "São Paulo",
      "Santiago",
      "Cusco",
      "Machu Picchu",
      "Cartagena",
      "Cancun",
      "Tulum",
      "Puerto Vallarta",
      "Puebla",
      "Merida",
      "Cabo San Lucas",
      "Los Cabos",
      "Playa del Carmen",
      "Nassau",
      "Freeport",
      "Paradise Island",
      "Eleuthera",
      "Harbour Island",
      "Bimini",
      "New Providence",
      "San Jose",
      "Liberia",
      "Tamarindo",
      "Playa Flamingo",
      "Jaco",
      "Monteverde",
      "Quepos",
      "Puerto Viejo",
      "Bocas del Toro",
      "Boquete",
      "David",
      "San Salvador",
      "Santa Ana",
      "San Miguel",
      "San Pedro Sula",
      "Tegucigalpa",
      "Roatan Island",
      "Puerto Plata",
      "Santiago de los Caballeros",
      "La Romana",
      "Punta Cana",
      "Samaná",
      "Cap-Haïtien",
      "Petionville",
      "Ocho Rios",
      "Negril",
      "Montego Bay",
      "Kingston",
      "Port Antonio",
      "Ponce",
      "Mayagüez",
      "Culebra",
      "Vieques",
      "Fajardo",
      "Arecibo",
      "Aguadilla",
      "Guayama",
      "Dorado",
      "Añasco",
      "Manatí",
      "Humacao",
      "Carolina",
      "Luquillo",
      "Bayamón",
      "Caguas",
      "San Juan",
      "Cayey",
      "Barceloneta",
      "Gurabo",
      "Vega Baja",
      "Yauco",
      "Coamo",
      "Las Piedras",
      "Santa Isabel",
      "Adjuntas",
      "Patillas",
      "Ceiba",
      "Cidra",
      "Comerio",
      "Juana Díaz",
      "Maunabo",
      "Morovis",
      "Naranjito",
      "Sabana Grande",
      "San Lorenzo",
      "Toa Alta",
      "Toa Baja",
      "Trujillo Alto",
      "Vega Alta",
      "Villalba",
      "Yabucoa",
      "Nueva Gerona",
      "Ciego de Ávila",
      "Camagüey",
      "Holguín",
      "Guantánamo",
      "Bayamo",
      "Santiago de Cuba",
      "Santa Clara",
      "Cienfuegos",
      "Pinar del Río",
      "Havana",
      "Varadero",
      "Viñales",
      "Trinidad",
      "Cayo Coco",
      "Cayo Santa María",
      "Guardalavaca",
      "Playa Pesquero",
      "Campeche",
      "Mérida",
      "Cancún",
      "Cozumel",
      "Isla Mujeres",
      "Playa del Carmen",
      "Puerto Morelos",
      "Tulum",
      "Akumal",
      "Chetumal",
      "Ciudad del Carmen",
      "Ixtapa",
      "Zihuatanejo",
      "Acapulco",
      "Puerto Escondido",
      "Oaxaca",
      "Huatulco",
      "San Cristóbal de las Casas",
      "Tuxtla Gutiérrez",
      "Tapachula",
      "Villahermosa",
      "Tampico",
      "Veracruz",
      "Xalapa",
      "Coatzacoalcos",
      "Oaxaca de Juárez",
      "Monterrey",
      "San Pedro Garza García",
      "Saltillo",
      "Parras de la Fuente",
      "Puerto Vallarta",
      "Zapopan",
      "Tlaquepaque",
      "Ajijic",
      "Sayulita",
      "Chapala",
      "Tequila",
      "Irapuato",
      "León",
      "Guanajuato",
      "San Jose",
      "Liberia",
      "Tamarindo",
      "Playa Flamingo",
      "Jaco",
      "Monteverde",
      "Quepos",
      "Puerto Viejo",
      "Bocas del Toro",
      "Boquete",
      "David",
      "San Salvador",
      "Santa Ana",
      "San Miguel",
      "San Pedro Sula",
      "Tegucigalpa",
      "Roatan Island",
      "San Juan del Sur",
      "Granada",
      "Leon",
      "Managua",
      "Ometepe Island",
      "Panama City",
      "Bocas del Toro",
      "David",
      "El Valle de Anton",
      "Colon",
      "Portobelo",
      "Willemstad",
      "Oranjestad",
      "Kralendijk",
      "Philipsburg",
      "Basseterre",
      "Castries",
      "Roseau",
      "Bridgetown",
      "Port of Spain",
      "Scarborough",
      "Kingstown",
      "Saint George's",
      "Belize City",
      "San Pedro",
      "Caye Caulker",
      "Ambergris Caye",
      "Tulum",
      "Cancun",
      "Playa del Carmen",
      "Cozumel",
      "Puerto Morelos",
      "Isla Mujeres",
      "Merida",
      "Oaxaca",
      "San Cristobal de las Casas",
      "Palenque",
      "Campeche",
      "Guadalajara",
      "Puerto Vallarta",
      "Sayulita",
      "Puebla",
      "Queretaro",
      "Mexico City",
      "Monterrey",
      "San Miguel de Allende",
      "Cabo San Lucas",
      "La Paz",
      "Los Cabos",
      "Puerto Escondido",
      "Zihuatanejo",
      "Acapulco",
      "Mazatlan",
      "Ixtapa",
      "Manzanillo",
      "Puerto Penasco",
      "Nassau",
      "Freeport",
      "Treasure Cay",
      "Marsh Harbour",
      "Green Turtle Cay",
      "Hope Town",
      "Exuma Cays",
      "George Town",
      "Eleuthera",
      "Harbour Island",
      "Governor's Harbour",
      "Bimini",
      "Long Island",
      "Grand Bahama Island",
      "New Providence",
      "Cayman Brac",
      "Grand Cayman",
      "Little Cayman",
      "Montego Bay",
      "Negril",
      "Ocho Rios",
      "Kingston",
      "Port Antonio",
      "Punta Cana",
      "Santo Domingo",
      "Puerto Plata",
      "Cabarete",
      "Santiago",
      "Las Terrenas",
      "Sosua",
      "Samana",
      "Cap-Haitien",
      "Jacmel",
      "Port-au-Prince",
      "Les Cayes",
      "Cienfuegos",
      "Havana",
      "Trinidad",
      "Santiago de Cuba",
      "Varadero",
      "Holguin",
      "Santa Clara",
      "Cayo Coco",
      "Camaguey",
      "Baracoa",
      "San Juan",
      "Ponce",
      "Rincon",
      "Mayaguez",
      "Aguadilla",
      "Humacao",
      "Fajardo",
      "Culebra",
      "Vieques",
      "Christiansted",
      "Frederiksted",
      "Road Town",
      "Tortola",
      "Virgin Gorda",
      "Anegada",
      "Jost Van Dyke",
      "St. Thomas",
      "St. John",
      "St. Croix",
      "St. Martin / St. Maarten",
      "St. Barthélemy",
      "Anguilla",
      "Antigua",
      "Aruba",
      "The Bahamas",
      "Barbados",
      "Belize",
      "Bermuda",
      "Bonaire",
      "British Virgin Islands",
      "Cayman Islands",
      "Cuba",
      "Curacao",
      "Dominica",
      "Dominican Republic",
      "Grenada",
      "Guadeloupe",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Martinique",
      "Mexico",
      "Montserrat",
      "Nicaragua",
      "Panama",
      "Puerto Rico",
      "Saba",
      "St. Eustatius",
      "St. Kitts and Nevis",
      "St. Lucia",
      "St. Vincent and the Grenadines",
      "Trinidad and Tobago",
      "Turks and Caicos Islands",
      "US Virgin Islands",
      "Venezuela",
      "Buenos Aires",
      "Córdoba",
      "Rosario",
      "Mendoza",
      "San Miguel de Tucumán",
      "La Plata",
      "Mar del Plata",
      "Salta",
      "Santa Fe",
      "San Juan",
      "Resistencia",
      "Corrientes",
      "Posadas",
      "Paraná",
      "Formosa",
      "Neuquén",
      "San Carlos de Bariloche",
      "Comodoro Rivadavia",
      "Bahía Blanca",
      "Santa Rosa",
      "San Luis",
      "Rawson",
      "Viedma",
      "Ushuaia",
      "Asunción",
      "Ciudad del Este",
      "Encarnación",
      "Luque",
      "Fernando de la Mora",
      "Lambare",
      "San Lorenzo",
      "Minga Guazu",
      "Pedro Juan Caballero",
      "Pilar",
      "Caacupe",
      "Coronel Oviedo",
      "Concepcion",
      "Villarrica",
      "Puerto Iguazu",
      "Salto",
      "Paysandu",
      "Montevideo",
      "Salinas",
      "Punta del Este",
      "Colonia del Sacramento",
      "Durazno",
      "Treinta y Tres",
      "Rivera",
      "Artigas",
      "Melilla",
      "Ceuta",
      "Tangier",
      "Marrakesh",
      "Casablanca",
      "Rabat",
      "Fes",
      "Agadir",
      "Essaouira",
      "Tétouan",
      "Meknes",
      "Ouarzazate",
      "El Jadida",
      "Chefchaouen",
      "Fez",
      "Gibraltar",
      "Algiers",
    ];

    // Filter the cities based on the search term
    const filteredCities = cities.filter((city) =>
      city.toLowerCase().startsWith(value)
    );

    setSuggestions(filteredCities);
  };

  const handleSelect = (city) => {
    setSearchTerm(city);
    setSuggestions([]);
    onLocationSelect(city);
  };

  return (
    <div>
      <input
        type="text"
        placeholder="Search for a city"
        value={searchTerm}
        onChange={handleSearch}
        style={{ marginTop: "10px" }}
      />

      {suggestions.length > 0 && (
        <ul
          style={{
            marginRight:'100px',
            marginLeft:'100px',
            height: "100px",
            overflowY: "scroll",
          }}
        >
          {suggestions.map((city) => (
            <li
              key={city}
              style={{
                backgroundColor: "whitesmoke",
                cursor: "pointer",
                border: "black",
                listStyleType: "none",
              }}
              onClick={() => handleSelect(city)}
            >
              {city}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default SearchBar;
