import React, { useState } from "react";

const SearchBar = ({ onLocationSelect }) => {
  const [searchTerm, setSearchTerm] = useState("");
  const [suggestions, setSuggestions] = useState([]);

  const handleSearch = (event) => {
    const value = event.target.value.toLowerCase();
    setSearchTerm(value);

    const cities = [
      "Tokyo",
      "Delhi",
      "Shanghai",
      "Sao Paulo",
      "Mumbai",
      "Mexico City",
      "Beijing",
      "Osaka",
      "Cairo",
      "New York",
      "Dhaka",
      "Karachi",
      "Buenos Aires",
      "Istanbul",
      "Chongqing",
      "Kolkata",
      "Manila",
      "Lagos",
      "Rio de Janeiro",
      "Tianjin",
      "Kinshasa",
      "Guangzhou",
      "Los Angeles",
      "Moscow",
      "Shenzhen",
      "Lahore",
      "Bangkok",
      "Jakarta",
      "Seoul",
      "Bangalore",
      "Chennai",
      "Lima",
      "Hyderabad",
      "Johannesburg",
      "Tehran",
      "Wuhan",
      "Ho Chi Minh City",
      "Luanda",
      "Ahmedabad",
      "Harbin",
      "Baghdad",
      "Surat",
      "Riyadh",
      "Santiago",
      "Pune",
      "Singapore",
      "Madrid",
      "Toronto",
      "Frankfurt",
      "Yangon",
      "Ankara",
      "Munich",
      "Paris",
      "Sydney",
      "Washington D.C.",
      "Seattle",
      "Dallas",
      "Atlanta",
      "Miami",
      "Philadelphia",
      "San Francisco",
      "Boston",
      "Phoenix",
      "Detroit",
      "Houston",
      "Riverside",
      "Chicago",
      "Montreal",
      "Vancouver",
      "Ottawa",
      "Calgary",
      "Edmonton",
      "Quebec City",
      "Winnipeg",
      "Halifax",
      "St. John's",
      "Santiago de Cuba",
      "Santo Domingo",
      "Havana",
      "Port-au-Prince",
      "Kingston",
      "San Juan",
      "Bridgetown",
      "Hamilton",
      "Nassau",
      "San Jose",
      "Belize City",
      "Tegucigalpa",
      "Managua",
      "San Salvador",
      "Panama City",
      "Willemstad",
      "Oranjestad",
      "Philipsburg",
      "Basseterre",
      "Roseau",
      "Saint John's",
      "Castries",
      "Saint George's",
      "Kingstown",
      "Port of Spain",
      "Caracas",
      "Bogotá",
      "La Paz",
      "Asuncion",
      "Montevideo",
      "Brasilia",
      "Rio de Janeiro",
      "São Paulo",
      "Santiago",
      "Quito",
      "Guayaquil",
      "Cusco",
      "Machu Picchu",
      "Cartagena",
      "Cancun",
      "Tulum",
      "Puerto Vallarta",
      "Guadalajara",
      "Puebla",
      "Merida",
      "Cabo San Lucas",
      "Los Cabos",
      "Playa del Carmen",
      "Nassau",
      "Freeport",
      "Paradise Island",
      "Eleuthera",
      "Harbour Island",
      "Bimini",
      "New Providence",
      "Bridgetown",
      "Kingston",
      "Port-au-Prince",
      "San Juan",
      "Santo Domingo",
      "Havana",
      "San Jose",
      "Managua",
      "Tegucigalpa",
      "Panama City",
      "Belize City",
      "Willemstad",
      "Oranjestad",
      "Philipsburg",
      "Basseterre",
      "Roseau",
      "Saint John's",
      "Castries",
      "Saint George's",
      "Kingstown",
      "Port of Spain",
      "Caracas",
      "Bogotá",
      "Quito",
      "La Paz",
      "Asuncion",
      "Montevideo",
      "Brasilia",
      "Rio de Janeiro",
      "São Paulo",
      "Santiago",
      "Cusco",
      "Machu Picchu",
      "Cartagena",
      "Cancun",
      "Tulum",
      "Puerto Vallarta",
      "Puebla",
      "Merida",
      "Cabo San Lucas",
      "Los Cabos",
      "Playa del Carmen",
      "Nassau",
      "Freeport",
      "Paradise Island",
      "Eleuthera",
      "Harbour Island",
      "Bimini",
      "New Providence",
      "George Town",
      "Bridgetown",
      "Kingston",
      "Port-au-Prince",
      "San Juan",
      "Santo Domingo",
      "Havana",
      "San Jose",
      "Managua",
      "Tegucigalpa",
      "Guatemala City",
      "Panama City",
      "Belize City",
      "Willemstad",
      "Oranjestad",
      "Philipsburg",
      "Basseterre",
      "Roseau",
      "Saint John's",
      "Castries",
      "Saint George's",
      "Kingstown",
      "Port of Spain",
      "Caracas",
      "Bogotá",
      "Quito",
      "La Paz",
      "Asuncion",
      "Montevideo",
      "Brasilia",
      "Rio de Janeiro",
      "São Paulo",
      "Santiago",
      "Cusco",
      "Machu Picchu",
      "Cartagena",
      "Cancun",
      "Tulum",
      "Puerto Vallarta",
      "Puebla",
      "Merida",
      "Cabo San Lucas",
      "Los Cabos",
      "Playa del Carmen",
      "Nassau",
      "Freeport",
      "Paradise Island",
      "Eleuthera",
      "Harbour Island",
      "Bimini",
      "New Providence",
      "San Jose",
      "Liberia",
      "Tamarindo",
      "Playa Flamingo",
      "Jaco",
      "Monteverde",
      "Quepos",
      "Puerto Viejo",
      "Bocas del Toro",
      "Boquete",
      "David",
      "San Salvador",
      "Santa Ana",
      "San Miguel",
      "San Pedro Sula",
      "Tegucigalpa",
      "Roatan Island",
      "Puerto Plata",
      "Santiago de los Caballeros",
      "La Romana",
      "Punta Cana",
      "Samaná",
      "Cap-Haïtien",
      "Petionville",
      "Ocho Rios",
      "Negril",
      "Montego Bay",
      "Kingston",
      "Port Antonio",
      "Ponce",
      "Mayagüez",
      "Culebra",
      "Vieques",
      "Fajardo",
      "Arecibo",
      "Aguadilla",
      "Guayama",
      "Dorado",
      "Añasco",
      "Manatí",
      "Humacao",
      "Carolina",
      "Luquillo",
      "Bayamón",
      "Caguas",
      "San Juan",
      "Cayey",
      "Barceloneta",
      "Gurabo",
      "Vega Baja",
      "Yauco",
      "Coamo",
      "Las Piedras",
      "Santa Isabel",
      "Adjuntas",
      "Patillas",
      "Ceiba",
      "Cidra",
      "Comerio",
      "Juana Díaz",
      "Maunabo",
      "Morovis",
      "Naranjito",
      "Sabana Grande",
      "San Lorenzo",
      "Toa Alta",
      "Toa Baja",
      "Trujillo Alto",
      "Vega Alta",
      "Villalba",
      "Yabucoa",
      "Nueva Gerona",
      "Ciego de Ávila",
      "Camagüey",
      "Holguín",
      "Guantánamo",
      "Bayamo",
      "Santiago de Cuba",
      "Santa Clara",
      "Cienfuegos",
      "Pinar del Río",
      "Havana",
      "Varadero",
      "Viñales",
      "Trinidad",
      "Cayo Coco",
      "Cayo Santa María",
      "Guardalavaca",
      "Playa Pesquero",
      "Campeche",
      "Mérida",
      "Cancún",
      "Cozumel",
      "Isla Mujeres",
      "Playa del Carmen",
      "Puerto Morelos",
      "Tulum",
      "Akumal",
      "Chetumal",
      "Ciudad del Carmen",
      "Ixtapa",
      "Zihuatanejo",
      "Acapulco",
      "Puerto Escondido",
      "Oaxaca",
      "Huatulco",
      "San Cristóbal de las Casas",
      "Tuxtla Gutiérrez",
      "Tapachula",
      "Villahermosa",
      "Tampico",
      "Veracruz",
      "Xalapa",
      "Coatzacoalcos",
      "Oaxaca de Juárez",
      "Monterrey",
      "San Pedro Garza García",
      "Saltillo",
      "Parras de la Fuente",
      "Puerto Vallarta",
      "Zapopan",
      "Tlaquepaque",
      "Ajijic",
      "Sayulita",
      "Chapala",
      "Tequila",
      "Irapuato",
      "León",
      "Guanajuato",
    ];

    // Filter the cities based on the search term
    const filteredCities = cities.filter((city) =>
      city.toLowerCase().startsWith(value)
    );

    setSuggestions(filteredCities);
  };

  const handleSelect = (city) => {
    setSearchTerm(city);
    setSuggestions([]);
    onLocationSelect(city);
  };

  return (
    <div>
      <input
        type="text"
        placeholder="Search for a city"
        value={searchTerm}
        onChange={handleSearch}
        style={{ marginTop: "10px" }}
      />

      {suggestions.length > 0 && (
        <ul style={{ paddingRight: "100px", paddingLeft: "100px" }}>
          {suggestions.map((city) => (
            <li
              key={city}
              style={{
                backgroundColor: "whitesmoke",
                cursor: "pointer",
                border: "black",
              }}
              onClick={() => handleSelect(city)}
            >
              {city}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default SearchBar;
